AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  addTicket:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: addTicket/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /tickets
            Method: POST
  addTicketPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - addTicket
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
  getTicketsForUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getTicketsForUser/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /tickets
            Method: GET
  getTicketsForUserPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - getTicketsForUser
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
  getTicketDetails:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getTicketDetails/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::369068112778:role/cloud9-Backend-addTicketRole-AU5Z0A806O98'
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: '/tickets/{ticketId}'
            Method: GET
  getTicketDetailsPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - getTicketDetails
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
  getRepliesForTicket:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getRepliesForTicket/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::369068112778:role/cloud9-Backend-addTicketRole-AU5Z0A806O98'
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: '/replies/{ticketId}'
            Method: GET
  getRepliesForTicketPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - getRepliesForTicket
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
  updateTicket:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: updateTicket/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::369068112778:role/cloud9-Backend-addTicketRole-AU5Z0A806O98'
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: '/ticket/{ticketId}'
            Method: POST
  updateTicketPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - updateTicket
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
  addReply:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: addReply/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::369068112778:role/cloud9-Backend-addTicketRole-AU5Z0A806O98'
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: '/replies/{ticketId}'
            Method: POST
  addReplyPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - addReply
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
  updateAccessToTicket:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: updateAccessToTicket/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::369068112778:role/cloud9-Backend-addTicketRole-AU5Z0A806O98'
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: '/access/{ticketId}'
            Method: PUT
  updateAccessToTicketPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - updateAccessToTicket
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
  getTicketAccessControlList:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getTicketAccessControlList/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::369068112778:role/cloud9-Backend-addTicketRole-AU5Z0A806O98'
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /access/{ticketId}
            Method: GET
  getTicketAccessControlListPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - getTicketAccessControlList
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
